### ISSUE TITLE
View All Speakersボタンの遷移先をスピーカー一覧にする

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/devfest#11]
https://tokyo.gdgjapan.org/ の `View All Speakers` のLink先が `/speakers` になっているので、これを `/2017/speakers` に変更する

![image](https://user-images.githubusercontent.com/446022/30238774-db867bc0-9588-11e7-9dc9-b71dc29cc3a2.png)

**Comment by soundTricker** [comment]
Finished by #18
