### ISSUE TITLE
mixed contentsの解消

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/devfest#13]
https://tokyo.gdgjapan.org/ で、mixed contentsの警告が表示される
httpで取ってる何かがあるっぽい

**Comment by k2wanko** [comment]
https://github.com/sinmetal/devfest/blob/6cee2c5510ae0b3a8f829952c10dadc110a6b65e/docs/devffest-tokyo2017-firebase-data.json#L390

**Comment by sinmetal** [comment]
なるほどな

**Comment by sinmetal** [comment]
done.
