### ISSUE TITLE
GDG Meta情報

### ISSUE THREAD

**Issue by sinmetal** [sinmetal/devfest#7]
## GDG Links

- [ ] twitter
- [ ] facebook
- [ ] G+
- [ ] WebSite

## What is GDG?

```
Google Developers Group (GDG) - is open and volunteer geek community who create exciting projects and share experience about Google technologies with a passion
```

## Organizer

```
GDG Lviv with support of 10 GDGs from all around Ukraine is proud organizer of DevFest Ukraine
```

## Team

https://devfest-tokyo.firebaseapp.com/team/

```
Google is known all around the world. Everyone is 'googling', checking on 'maps' and communicating in 'gmail'. For simple users, they are services that just works, but not for us. Developers see much more: APIs, scalability issues, complex technology stacks. And that is what GDG is about.

Google Developers Group (GDG) Lviv - is open and volunteer geek community who create exciting projects and share experience about Google technologies with a passion.

Our goal is to organize space to connect the best industry experts with Ukrainian audience to boost development of IT.
```

**Comment by nomadkoala** [comment]
## GDG Links

(なし?)

## ハッシュタグ
#DevFest17

## WHAT IS GDG?
Google Developer Group (GDG) は、主に Google のテクノロジーに興味のある人たちで情報を共有しあうコミュニティです。

## Organizer
DevFest Tokyo のオーガナイザーは、東京で活躍している 14 のコミュニティです。

## Team
東京では、毎月数え切れないほどの勉強会が開催されていますが、イベントが重複したり会場を見つけるのが大変だったり、アクティブなコミュニティが多いゆえの悩みがあったりします。多くのデベロッパーがハッピーに情報を共有していくにはどうしたらよいのか？そして、新しく勉強会に来たいと思っている人や他のプロダクトについて勉強したいと思っている人へ提供できるものは何か？そんなことを考え、東京の14のコミュニティが結集し、このDevFestのオーガナイザーは成り立っています。
=> 下に各コミュニティのロゴを入れる？

**Comment by sinmetal** [comment]
done.
